### ISSUE TITLE
how to load on cpanel

### ISSUE THREAD

**Issue by gulonline** [anthony-mills/CryptoCoins#1]
can you please tell me how to load this on cpanel ?

**Comment by anthony-mills** [comment]
I cannot give direction without knowledge of what exactly your hosting environment entails. If you have SSH access to the host then I suggest you read this page [about using composer with cPanel](https://documentation.cpanel.net/display/CKB/How+to+Set+Up+%28PHP%29+Composer).  Beyond this you will need to create a MySQL database in the admin panel import the SQL dump found in sql/ folder of the code base and add your database parameters to the application config file in the config/ directory.
